### ISSUE TITLE
Investigate Click-path for someone looking for the original TIFF/JP2 for a georeferenced map

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#82] opened 2014-12-05 22:27 UTC

**Comment by mejackreed** [comment] 2015-03-03 22:46
Currently no prod data that has this.

**Comment by thatbudakguy** [comment] 2024-02-23 19:55
plenty of prod data that has this now, but you still can't easily download .jp2s from the sul-embed viewer or PURL, it seems like.

**Comment by dnoneill** [comment] 2024-07-12 19:10
Do we still need this since there is a path in sul-embed?

**Comment by thatbudakguy** [comment] 2024-07-12 21:31
We need to check if you can still get it for things that aren't stanford, and thus aren't using sul-embed

**Comment by dnoneill** [comment] 2024-07-12 21:41
Looks like all have a download original jpeg
Minnesota: https://earthworks.stanford.edu/catalog/p16022coll247:310
Indiana: https://earthworks.stanford.edu/catalog/VAC3073-M-00794 \
Rutgers: https://earthworks.stanford.edu/catalog/rutgers-lib:29184

**Comment by thatbudakguy** [comment] 2024-07-19 18:36
I think the issue is that we don't want the jpg (which is a IIIF link) but the actual underlying JP2 that the image server is referencing. Although "why" is a good question...

**Comment by thatbudakguy** [comment] 2024-07-22 17:48
Seems like for non-Stanford stuff people would need to include their own special key in `dct_references_s` allowing the JP2 download, which we can't expect people to do. Since this is resolved for Stanford content by the usage of sul-embed, I'm going to close it.

**Closed by thatbudakguy** 2024-07-22 17:48 UTC
