### ISSUE TITLE
large datasets fail to download via Generated links

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#272] opened 2015-06-17 18:02 UTC
Example:

  https://earthworks.stanford.edu/catalog/stanford-kr064yh0964

This download works when going directly to the GeoServer after a minute or so. The SHAPE-ZIP is over 700MB. But the download fails in EarthWorks.

![screen shot 2015-06-17 at 11 01 20 am](https://cloud.githubusercontent.com/assets/1861171/8214757/364a5dd2-14e0-11e5-9c52-0b8681a4aaf9.png)

**Comment by mejackreed** [comment] 2015-06-17 18:07
with #269 we can precache these downloads

**Comment by thatbudakguy** [comment] 2023-04-18 21:04
might be addressed by https://github.com/geoblacklight/geoblacklight/issues/294

**Comment by peetucket** [comment] 2024-07-15 16:48
Note: I was just able to download the 1.2 gb shapefile zip from https://earthworks.stanford.edu/catalog/stanford-kr064yh0964 without error

**Comment by edsu** [comment] 2024-07-15 17:09
Oh hmm, 1.2 GB > 700 MB ... maybe this can be closed?

**Comment by peetucket** [comment] 2024-07-15 18:42
I think unless someone can reproduce it, I would argue it should be closed.  The error message shown at the top of the ticket suggests it was more than just a timeout (i.e. independent of connection speed).

**Comment by kimdurante** [comment] 2024-07-15 20:13
I am still getting an error when trying to download this file using the Download > Export Shapefile link. This is the WGS84 derivative (EPSG:4326). Are you able to download this file?

The Download options are a little confusing currently. However, in Darcy's new design the Export shapefile states WGS84 in the export link.

**Comment by edsu** [comment] 2024-07-15 20:46
Perhaps related we noticed `/tmp/` filling up in a similar time frame to when this testing happened.  From Slack:

> a few minutes ago /tmp on earthworks-geoserver-stan-prod-b just got filled up by  /tmp//systemd-private-b01df36c269c4058b1ebb64cd75bd83a-tomcat9.service-FXKN8i/tmp Not sure what triggered tomcat to  generate this spike.   /tmp being full can cause weird behaviors like not being able to login to the server.

**Comment by peetucket** [comment] 2024-07-16 16:45
Do we know of any large datasets in stage that we could use to trigger this error?  Trying to think of a better way of tracking without impacting prod.

As @hudajkhan  noted in slack, first click to download should cause the file to be created in the space defined in `Settings.DOWNLOAD_PATH`, then display a message saying it is ready.  After that, clicking to download should just retrieve the file that was previously created in the download path (unless it was cleared by our new cache cleaner).  It's not clear where `tmp` gets entered into this, as the download path in the settings is not the tmp drive.  It is also not clear why large files are failing to be created.

**Comment by peetucket** [comment] 2024-07-16 17:25
In stage, geoserver is possibly timing out:

Tried clicking `Export GeoTIFF` here: https://earthworks-stage.stanford.edu/catalog/stanford-rz417vq6403 and eventually got the error mesage on the webpage.

I was watching the production log on `earthworks-stage-a` and could see the incoming request to download:

```
I, [2024-07-16T10:19:38.155575 #643096]  INFO -- : [9e06e55a-2a56-42b5-bfb6-92a10e00ec0a] Started GET "/download/stanford-rz417vq6403?type=geotiff" for 10.130.142.53
```

But it is followed a bit later by this, which could be related:

```
E, [2024-07-16T10:19:54.211063 #643096] ERROR -- : [9e06e55a-2a56-42b5-bfb6-92a10e00ec0a] Download timed out https://earthworks-geoserver-stage-b.stanford.edu/geoserver/wms/reflect
```

Indeed the file is not generated as it should have been in `/var/cache/earthworks/downloads`

**Comment by peetucket** [comment] 2024-07-16 17:27
Clicking `Export GeoTIFF` does work on stage though with this object: https://earthworks-stage.stanford.edu/catalog/stanford-kx853bc3354

and creates the file successfully

**Comment by peetucket** [comment] 2024-07-16 20:23
Some debugging confirming we cannot currently create the geotiff on stage for https://earthworks-stage.stanford.edu/catalog/stanford-rz417vq6403.  Problem appears to be a timeout from https://earthworks-geoserver-stage-b.stanford.edu

Rails console on earthworks-stage running the code that would be executed when the user requests to `Export GeoTIFF`:

```
id='stanford-rz417vq6403'
document = SolrDocument.find(id)
document.downloadable?
 => true
geotiff = Geoblacklight::GeotiffDownload.new(document)
geotiff.file_path_and_name
 => "/var/cache/earthworks/downloads/stanford-rz417vq6403-geotiff.tif"
geotiff.create_download_file
in `<main>': Download timed out (Geoblacklight::Exceptions::ExternalDownloadFailed)
/opt/app/geostaff/earthworks/shared/bundle/ruby/3.2.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:229:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Faraday::TimeoutError)
geotiff.url_with_params
 => "https://earthworks-geoserver-stage-b.stanford.edu/geoserver/wms/reflect/?format=image%2Fgeotiff&width=4096&layers=druid%3Arz417vq6403"
3.2.0 :013 >
```

Timeout is currently 16 seconds as set in the settings:

```
geotiff.send(:timeout)
 => 16

Settings.TIMEOUT_DOWNLOAD
 => 16
```

Increasing the timeout had no effect (still timed out):

```
geotiff = Geoblacklight::GeotiffDownload.new(document, timeout: 60)
geotiff.send(:timeout)
 => 16
geotiff.create_download_file
in `<main>': Download timed out (Geoblacklight::Exceptions::ExternalDownloadFailed)
/opt/app/geostaff/earthworks/shared/bundle/ruby/3.2.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:229:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Faraday::TimeoutError)

```

**Comment by peetucket** [comment] 2024-07-16 20:31
Timeout bumped higher still, and hit a different exception:

```
geotiff = Geoblacklight::GeotiffDownload.new(document, timeout: 300)
geotiff.send(:timeout)
geotiff.url_with_params
 => "https://earthworks-geoserver-stage-b.stanford.edu/geoserver/wms/reflect/?format=image%2Fgeotiff&width=4096&layers=druid%3Arz417vq6403"
geotiff.create_download_file
Geoblacklight::Exceptions::WrongDownloadFormat expected image/geotiff received text/html; charset=iso-8859-1
(irb):23:in `<main>': Wrong download type (Geoblacklight::Exceptions::ExternalDownloadFailed)
/opt/app/geostaff/earthworks/shared/bundle/ruby/3.2.0/bundler/gems/geoblacklight-24aba2e82f4b/lib/geoblacklight/download.rb:46:in `block in create_download_file': Geoblacklight::Exceptions::WrongDownloadFormat (Geoblacklight::Exceptions::WrongDownloadFormat)

```

Using admin interface on geoserver to request the geotiff by searching for `rz417vq6403` here: https://earthworks-geoserver-stage-b.stanford.edu/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?8&filter=false

Eventually returned a 500.

**Comment by peetucket** [comment] 2024-07-16 21:36
Just tried the shapefile in prod for the problematic example druid above and it times out:

```
id='stanford-kr064yh0964'
document=SolrDocument.find(id)
shapefile=Geoblacklight::ShapefileDownload.new(document)
shapefile.send(:timeout)
 => 16
shapefile.file_path_and_name
 => "/var/cache/earthworks/downloads/stanford-kr064yh0964-shapefile.zip"
shapefile.download_exists?
 => false
shapefile.send(:url)
 => "https://geowebservices-restricted.stanford.edu/geoserver/wfs"
shapefile.create_download_file
(irb):9:in `<main>': Download timed out (Geoblacklight::Exceptions::ExternalDownloadFailed)
/opt/app/geostaff/earthworks/shared/bundle/ruby/3.2.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:229:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Faraday::TimeoutError)
```


Increasing the timeout and it worked.  So the default timeout of 16 is too short for this file.  I just made a big jump up to 300, it seemed to actually take 60-70 seconds or so.

```
shapefile=Geoblacklight::ShapefileDownload.new(document, timeout: 300)
shapefile.send(:timeout)
 => 300
shapefile.create_download_file
 => "stanford-kr064yh0964-shapefile.zip"
shapefile.download_exists?
 => true
```

Go to browser and try to download shapefile and it works (the file is now there):  https://earthworks.stanford.edu/catalog/stanford-kr064yh0964

**Comment by kimdurante** [comment] 2024-07-16 21:44
Works for me!

**Comment by peetucket** [comment] 2024-07-16 22:46
Some more debugging for the failed download on stage for https://earthworks-stage.stanford.edu/catalog/stanford-rz417vq6403  

I am bypassing some code that swallows errors and raises them separately to see what geoserver is actually responding with. Definitely appears that geoserver is unhappy with that data:

```
id='stanford-rz417vq6403'
document = SolrDocument.find(id)
geotiff = Geoblacklight::GeotiffDownload.new(document, timeout: 200)
download = geotiff.initiate_download
download.status # good
 => 200 
download.body # not good
 => "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ServiceExceptionReport version=\"1.3.0\" xmlns=\"http://www.opengis.net/ogc\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.opengis.net/ogc https://earthworks-geoserver-stage-b.stanford.edu/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd\">   <ServiceException>\n      Error rendering coverage on the fast path\njava.lang.RuntimeException: Failed to mosaic the input coverages\nFailed to mosaic the input coverages\nAll factories fail for the operation &quot;Mosaic&quot;Java heap space\n</ServiceException></ServiceExceptionReport>" 
```

**Closed** 2024-07-19 19:22 UTC
Labels: bug
