### ISSUE TITLE
Re-Harvest records from OpenGeoMetadata

### ISSUE THREAD

**Issue by kimdurante** [sul-dlss/earthworks#836] opened 2022-01-19 16:14 UTC
Many of the records in EarthWorks from OpenGeoMetadata are out of date. External institutions have added/updated their metadata since our last harvest, resulting in data showing as unavailable. Example from Harvard's collection:

https://earthworks.stanford.edu/catalog/harvard-g8964-a2-1876-l3

This is also true for other institutions (NYU, Princeton, etc.). This was reported to me by Harvard staff who were hearing from end users about not being able to access content through EarthWorks. They said it was not extremely urgent. 

A regularly-scheduled harvest of content from OpenGeoMetadata would be ideal. However, a one-time refresh would suffice for now. We will be looking at changes in the coming year related to the metadata schema, so perhaps we can look into any changes related to the harvesting process at that time as well. 

Thanks! Please let me know if you need any other information.

**Comment by thatbudakguy** [comment] 2022-02-25 21:03
marking this as a duplicate of #591, but adding this comment there so we don't lose it — thx @kimdurante

**Closed by thatbudakguy** 2022-02-25 21:03 UTC
Labels: duplicate
