### ISSUE TITLE
Reharvest all of Columbia's md

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#305] opened 2016-06-23 18:35 UTC
https://github.com/OpenGeoMetadata/edu.columbia

**Comment by drh-stanford** [comment] 2016-07-29 21:55
There's some weird slugs in these metadata, so I'm normalizing them with this:

```ruby
doc['layer_slug_s'].gsub!(/[^[[:alnum:]]]+/, '-') # normalize to alphanum and - only
```

**Comment by drh-stanford** [comment] 2016-08-01 20:22
See -dev index

**Comment by drh-stanford** [comment] 2017-12-08 18:53
Duplicate of #337

**Closed by drh-stanford** 2017-12-08 18:53 UTC
Labels: data
